obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.27, -0.27], [-0.27, 0.27], [0.27, 0.27], [0.27, -0.27]] 
#robot_radius: 0.105

inflation_radius: 0.3
cost_scaling_factor: 10.0

map_type: costmap
observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true

